// swift-tools-version: 5.9

// WARNING:
// This file is generated by Apple Swift Playgrounds / Xcode.
// DO NOT EDIT THIS FILE DIRECTLY UNLESS CONFIGURED FOR WWDC SWIFT STUDENT CHALLENGE.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MountAIScholar",
    defaultLocalization: "fr",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [
        .iOSApplication(
            name: "Mount AI Scholar",
            targets: ["AppModule"],
            bundleIdentifier: "com.mentora.mountaischolar",
            teamIdentifier: "",
            displayVersion: "1.0.0",
            bundleVersion: "1",
            appIcon: .placeholder(placeholder: .brain),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Mount AI Scholar analyse en temps réel les signes dactylologiques et supports visuels à 120 FPS via l'Apple Neural Engine."),
                .microphone(purposeString: "Mount AI Scholar effectue la reconnaissance vocale phonologique locale 100% On-Device sans transfert de données."),
                .speechRecognition(purposeString: "Transcription phonème-graphème locale pour l'assistance à la lecture dyslexique.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
